### ISSUE TITLE
Whether the natural number contains 0

### ISSUE THREAD

**Issue by JameWade** [LeastAuthority/moonmath-manual#100]
Here it is said that natural numbers do not include 0
![image](https://github.com/LeastAuthority/moonmath-manual/assets/47301518/44f50e62-c02e-4fa4-b4a7-bd388dd45dc9)

and Here it is said that the natural number r can be equal to 0
![image](https://github.com/LeastAuthority/moonmath-manual/assets/47301518/552cbf99-691f-4e74-817f-1527d9653f2f)

**Comment by PlanetMacro** [comment]
good point. we'll update it in the next version update.
