### ISSUE TITLE
Wrong formula in Example 58

### ISSUE THREAD

**Issue by hk-lin** [LeastAuthority/moonmath-manual#105]
In 4.3.26，it prsent：
![image](https://github.com/LeastAuthority/moonmath-manual/assets/26270262/8cb7de36-395c-4288-b405-1be610fb6b37)
So for k = |16|2 = 5, the largest exponent should be k-2 = 3.But in example 58, it's formula is:
![image](https://github.com/LeastAuthority/moonmath-manual/assets/26270262/82b4c062-ccd7-4d36-a6ed-995632616dd9)
It will distribute in set {0...31},not {0..15}:
![image](https://github.com/LeastAuthority/moonmath-manual/assets/26270262/e86d9b0c-457a-49a5-84e9-08218ed095f5)

So it's a fault.

**Comment by PlanetMacro** [comment]
Right. See also #92 ... We changed the hash function and also the sage code to not project to Z_16 in the end
