### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by Honglei-Cong** [LeastAuthority/moonmath-manual#21]
https://github.com/LeastAuthority/moonmath-manual/blob/6569acbdae0e469e21b7088703c0eef54c42b289/chapters/arithmetics-moonmath.tex#L1046

`$(x-3)(x+3)= x^2 -3x +3x -3\cdot 3= x^2-9$.`

**Comment by PlanetMacro** [comment]
Thanks for the comment. In line 1046, computation in done over modular 6 arithmetic. In this case $-3 * 3 = 3 * 3 = 3$. See the section on modular arithmetic for an explanation.
