### ISSUE TITLE
Avoid generalizing verifier smart contracts as ZK-rollups 

### ISSUE THREAD

**Issue by alxkzmn** [LeastAuthority/moonmath-manual#27]
https://github.com/LeastAuthority/moonmath-manual/blob/cc17cc763ed29b0f84c7af44485a3e9d6512e5bc/chapters/intro-moonmath.tex#L7

A general way of interaction with an on-chain verifier described there is not the same as a ZK-rollup. While ZK-rollups indeed involve ZKP verification done by a smart contract, they represent a very specific case of a blockchain ZKP application. ZK-rollups are usually ledgers similar to blockchains, and they "roll up" multiple transactions into a single succinct proof. At the same time, there are some significant blockchain ZKP applications that do not involve a ledger and do not "roll up" multiple transactions, e.g., Tornado Cash.

**Comment by PlanetMacro** [comment]
Hey. If you are referring to a generally agreed on definition of what a zk-rollup is, please share the link, so we can verify.
