### ISSUE TITLE
Group identity (neutral) element property definition.

### ISSUE THREAD

**Issue by GianfrancoBazzani** [LeastAuthority/moonmath-manual#28]
In the book the identity (neutral) element property of the groups is defined as follows:
![image](https://user-images.githubusercontent.com/55500596/199592397-5c230ac3-6c3e-46e7-b721-3b98e4e2cb98.png)

But wikipedia gives following definition for abelian groups:
![image](https://user-images.githubusercontent.com/55500596/199593011-6ecfaa5c-88cc-49a7-b75a-d35761222f1f.png)
 
it is similar but different, which one is the correct one?

**Comment by PlanetMacro** [comment]
The Wikipedia definition is the correct one for groups. However if a group is commutative, then because a*b = b*a choosing one of the defining equations is enough.
