### ISSUE TITLE
Error in (5.44) in the Elliptic Curve Chapter Page 101

### ISSUE THREAD

**Issue by RisenCrypto** [LeastAuthority/moonmath-manual#30]
Page 101.

There is something wrong here - https://imgur.com/waKpwoY.png

The first line says E(F_p^k)[r] is a **subset of** E(F_p^{k+1)[r]
The 2nd line says E(F_p^k)[r] is **equal to** E(F_p^{k+1)[r]

The 2nd line obviously correct, but I am not sure what the 1st line was supposed to be.

----  

Another issue on Pg 105.

https://imgur.com/HSNJCZ6.png

In example 93, this program is shown as the program which computes G2. But this obviously is not the program which was meant to be there - the program shown is a hashing program rather than program which computes G2.

**Comment by RisenCrypto** [comment]
Another issue on Pg 105.

https://imgur.com/HSNJCZ6.png

In example 93, this program is show as the program which computes G2. But this obviously is not the program which was meant to be there - the program shown is a hashing program rather than program which computes G2.

**Comment by PlanetMacro** [comment]
Ah yes thanks. In the first line there should be the curve E(.) not the r-torsion E(,)[r]. We'll correct that.

**Comment by PlanetMacro** [comment]
Regarding Pg 105.. Correct. We have to rerun sagemath, I guess

**Comment by RisenCrypto** [comment]
One more misplaced sage program - Page 107 - https://imgur.com/Iq1k3kK.png

**Comment by wuan** [comment]
The broken references to sage snippets will be fixed by #32 as all intermediate files will be regenerated for every document build.
