### ISSUE TITLE
Montgomery Curve's Short Weierstrass form

### ISSUE THREAD

**Issue by 0xbok** [LeastAuthority/moonmath-manual#31]
The definition of Short Weierstrass form associated with a Montgomery Curves is (on page 90):
<img width="849" alt="Screenshot 2022-11-16 at 16 40 02" src="https://user-images.githubusercontent.com/1689531/202165186-becc3edd-5f84-4109-99d7-adbbfb31c341.png">

However, `q` used in this definition is not defined.

**Comment by PlanetMacro** [comment]
Right. MMM is updated restricting the definition of Montgomery curves to curves over prime fields and changing the equation accordingly
