### ISSUE TITLE
Twisted Edwards group law

### ISSUE THREAD

**Issue by 0xbok** [LeastAuthority/moonmath-manual#33]
A suggestion:

The Twisted Edwards group law sections states that "group law of SNARK-friendly Twisted Edwards curves can be described by a single computation that works in all cases". However, it's not clear from the proceeding definition on how specifically the SNARK-friendliness plays a role. The definition is described for a general Twisted Edwards Curve which is also a single computation for all cases.

https://github.com/LeastAuthority/moonmath-manual/blob/f09ade1632a4a4a8ebcc0c33afc83aa987a186ba/chapters/elliptic-curves-moonmath.tex#L998

<img width="1104" alt="Screenshot 2022-11-17 at 00 14 43" src="https://user-images.githubusercontent.com/1689531/202266347-0e657b19-13b3-4701-9ed8-2bef95801011.png">

Would be good to clarify this in this section.

**Comment by PlanetMacro** [comment]
The usual definition of general twisted Edwards curve does not require the parameters a and d to satisfy anything other then being non-zero. In this case the addition law is not necessarily complete. 

However if a is a square in the field and d is a non-square , these formulas are complete. We call this SNARK friendly as complete equations are desired in circuits.

I wrote a few words into the book to make this point more clear
