### ISSUE TITLE
Typo in elliptic curve addition tangent rule formula on page 77

### ISSUE THREAD

**Issue by taetaehoho** [LeastAuthority/moonmath-manual#34]
Hey, think y' shouldn't have a squared here on the tangent rule. 
<img width="820" alt="Screen Shot 2022-11-18 at 1 01 52 AM" src="https://user-images.githubusercontent.com/75167060/202510353-16701951-5b17-4b15-9b14-7949c62b8984.png">

**Comment by PlanetMacro** [comment]
Right the equation for the y-coordinate was wrong (x-coordinates should be correct)
