### ISSUE TITLE
Version in the frontpage

### ISSUE THREAD

**Issue by davxy** [LeastAuthority/moonmath-manual#42]
It would be useful to have the book frontpage version aligned with the release version

E.g. the release 1.0.2 has 1.0.0 as frontpage version.

In this way I could be immediately confident about what version I'm reading to. Otherwise there is no immediate way to differentiate between two releases artifacts

**Comment by wuan** [comment]
This has already been addressed in #40. The next release will have a updated version on the first page.

You can preview that feature when looking at the PDF which has been produced by a recent build.
