### ISSUE TITLE
Isomorphic affine short Weierstrass curves

### ISSUE THREAD

**Issue by davxy** [LeastAuthority/moonmath-manual#44]
On page.77 , in **Example 74** is shown that, using the mapping `(x,y) -> (x' = x* c^2, y' = y * c^2)`
the point (4,3) in E_11(F) is mapped into the point (1,2) in E_14(F).

But looks like (1,2) is not a point in the curve E_14, that is composed by the points: `{O, (0, 2), (0, 3), (1, 1), (1, 4), (2, 2), (2, 3), (3, 2), (3, 3)}`

Do I missed something?

---

There is also a typo in the same example `y^3 = x^3 + x + 4` , but should be y^2

Thank you

**Comment by davxy** [comment]
I've empirically checked that `(x,y) -> (c^2*x, c^3*y)` works... but maybe that's just luck :-D

**Comment by davxy** [comment]
I also tried to went through the Excercise 62. But I don't think that tiny-jj and E_(5,12) are isomorphic.

Indeed tiny-jj points are 20 while E_(5,12) points are only 8.

This is the code to brutally get all the points excluded the point at inf (for sure there are better ways to do that, but I'm not confident with sage libs):

```python
def get_points(E, m):
    points = []
    for x in range(0, m):
        for y in range(0,m):
            try:
                E(x, y)
                points.append((x, y))
            except:
                pass
    return points
```

Now for tiny-jj:
```
> F13 = GF(13)
> E = EllipticCurve(F13, [8, 8])
> get_points(E, 13)
[(1, 2), (1, 11), (4,0), (5,2), (5,11), (6,5), (6,8), (7,2), (7,11), (8,5), (8,8), (9,4), (9,9), (10,3), (10,10),(11,6),(11,7),(12,5),(12,8)]
```

While for E_(5,12)
```
> E = EllipticCurve(F13, [8, 8])
> get_points(E, 13)
[(0,5), (0,8), (2,2), (2,11), (7,0), (10,3), (10,10)]
```

**Comment by davxy** [comment]
This is a valid curve isomorphic to tiny-jj (according to the book def):

Lets pick one c in F13, e.g. 6.

Given that tiny-jj a=8 and b=8, using the formula we get:
a' = 8*6^4 = 7
b' = 8*6^6 = 5

This curve has 20 points, as tiny-jj, and furthermore the mapping: (x,y) -> (x' = x*c^2, y' = y*c^3)
                                                                                                           
 Note that doesn't work if instead I use y' = y*c^2

**Comment by davxy** [comment]
Sorry for the long analysis. If you agree with the fix I can prepare a PR

**Comment by PlanetMacro** [comment]
Thanks. Yes the isomorphism in your first post has a typo, as well as the curve equation.

Exercise 62 makes no sense. I think what we meant was an isomorphism between E_{1,4}(F_5) and E_{5,12}(F_5). We'll update it soon and also include your tiny-jj isomorphic curve if that is ok with you?

**Comment by davxy** [comment]
@PlanetMacro yeah sure. You can use it.

What is the preferred channel for the team to submit typo corrections I've found while reading the book?
Most of the stuff I've found are trivial errors, but I think you may want to correct them in order to improve the book quality.

Do you prefer a single issue with everything I've found? Directly a PR (I already have one open)? Other channels (e.g. if you have a user group or something...)

**Comment by PlanetMacro** [comment]
PR is fine.
