### ISSUE TITLE
What is $h$ in the definition of QAP?

### ISSUE THREAD

**Issue by upavloff** [LeastAuthority/moonmath-manual#54]
<img width="911" alt="Screenshot 2023-02-26 at 22 16 55" src="https://user-images.githubusercontent.com/32176478/221437826-f1d58508-6826-497c-b434-cae50830465c.png">

**Comment by PlanetMacro** [comment]
THanks, that shoud be a j of course. We'll update it in the next version.

**Comment by upavloff** [comment]
For similar mistakes, I proposed changes as pull requests instead of issues. I mention this here just so you take them into account for the update as well.
