### ISSUE TITLE
Equation that is "parametrized by a_0" doesn't depend on a_0

### ISSUE THREAD

**Issue by pdg744** [LeastAuthority/moonmath-manual#60]
https://github.com/LeastAuthority/moonmath-manual/blob/b7787aacb3f4fe796f5ca2b2f051d63c6971b251/chapters/algebra-moonmath.tex#L618

This equation is described as being parametrized by $a_0, a_1, ..., a_n$ but $a_0$ doesn't appear in the equation.

**Comment by PlanetMacro** [comment]
Right. We'll change it in the next version. a_0 is not port of the parameterization

**Comment by PlanetMacro** [comment]
Ok, change b_0 to a_0 as in the definition of the Naor-Reingold PRF (See 3.3 in https://eprint.iacr.org/2016/492.pdf)
