### ISSUE TITLE
include_plonk_branch in a usable state?

### ISSUE THREAD

**Issue by dbrans** [LeastAuthority/moonmath-manual#67]
Hi @PlanetMacro,

I'm facilitating a study group based on the MoonMath Manual:
https://bit.ly/moonmathmanual

Many folks are interested in learning about polynomial commitment schemes, which is absent from the current version of the manual.

What state is the include_plonk_branch state in? Are parts of it usable for the purposes of a study group?

We appreciate all your work!

Derek

**Comment by PlanetMacro** [comment]
Its work in progress. Not really usable at this point.
