### ISSUE TITLE
Counterexample to Exercise 29

### ISSUE THREAD

**Issue by pdg744** [LeastAuthority/moonmath-manual#72]
Exercise 29 should be revised -- `f(x)=x^3` and `g(x)=(x-1)^2` are both counterexamples. 

More broadly, I think this chapter should include some mention of the idea of *multiplicity of roots*.

**Comment by PlanetMacro** [comment]
I think this is an issue of terminology. Both your examples have deg(P) many roots. It is not required that those roots are necessarily different.
