### ISSUE TITLE
Identification of Typos in the PDF Document - Request for Revision

### ISSUE THREAD

**Issue by luksgrin** [LeastAuthority/moonmath-manual#73]
I am (re-)reading the latest version of the moonmath (August 5th, 2023) manual and I noticed several typographical errors throughout its pages.
I will be updating this issue with my findings

- [ ] Page 9, exercise 4 "the set ofnatural numbers" should be "the set of natural numbers".
- [ ] Page 10, remark 1: "amd the operator" should be "and the operator".

**Comment by PlanetMacro** [comment]
Should be resolved now.
