### ISSUE TITLE
Map (4.27) on Page 51

### ISSUE THREAD

**Issue by xrypto-star** [LeastAuthority/moonmath-manual#74]
I think the map should look like this:

 $F_{\\{a_0, a_1,\ldots,a_k\\}} : \\{0,1\\}^k \to \mathbb{G} : (b_1,b_2,\ldots,b_k) \to g^{a_0 \Pi_{i=1}^k  a_i^{b_i}}$

**Comment by PlanetMacro** [comment]
yes
