### ISSUE TITLE
About maintenance

### ISSUE THREAD

**Issue by virackson** [LeastAuthority/moonmath-manual#82]
Hello! I've noticed that the number of open pull requests is growing without being reviewed.

I don't see this huge amount of PRs to justify something like "we are overwhelmed" by the contributions and we are slowly processing them.

I believe this project has a great potential but also needs appropriate maintenance to encourage community contributions.

Unfortunately, if I'm not wrong (I'm not lawyer), given the No-Derivatives clause independent extension of the work is not an option.

Maybe a good idea is to start building a community around this project and then offload the maintenance to some  "trusted" community members?

BTW. Thank you for your awesome work and sorry if the issue content may sound a bit too harsh, I'm just trying to understand... in the first place because I love this project

**Comment by skytools** [comment]
Hello @virackson , 
I am Sara, PM of the MMM Project.Thank you for sharing your concerns. 

As you have notices we are a small team. We need to balance our resources and time between different paid and unpaid projects, so we are not always able to advance on certain things as fast as we wish.

But rest assured that we are keep working on the MMM and we have some updates scheduled for the coming months.
We appreciate all the support and interest we get from the community. If you want to support us please keep us helping with PRs to suggest correction or improvement. Also, the MMM is a free resource and we appreciate any donation made to support the project.
