### ISSUE TITLE
Set definition 4.47

### ISSUE THREAD

**Issue by muellerberndt** [LeastAuthority/moonmath-manual#89]
There appears to be a minor bug in the definition:

$$\{F_{p^m}} := \{ a_{m-1}x^{m-1} + a_{k-2}x^{k-2} + \cdots + a_1x + a_0 \mid a_i \in \mathbb{F}_p \}$$

Should be:

$$\{F_{p^m}} := \{ a_{m-1}x^{m-1} + a_{m-2}x^{m-2} + \cdots + a_1x + a_0 \mid a_i \in \mathbb{F}_p \}$$

I.e. `m-2` as the second index/exponent instead of `k-2`.

**Comment by PlanetMacro** [comment]
Right. changed
