### ISSUE TITLE
Example 58 seems to be wrong

### ISSUE THREAD

**Issue by krehermann** [LeastAuthority/moonmath-manual#92]
Hi,

I'm working through the manual. Thank you for providing it, it is a great resource.

I believe the Example 58 is wrong.

```Example 58. To analyze a particular implementation of a H|n|2−1 hash function, we use a 5-bit truncation of the SHA256 hash from example 47 and define a hash into Z16 as follows:
H|16|2−5 : {0,1}∗ → Z_16 : s 7→ SHA256(s)_0 ·2^0 +SHAH256(s)_1 ·2^1 +...+SHA256(s)_4 ·2^4
Since k = |16|2 = 5 and 16 − 2k−1 = 0, this hash maps uniformly onto Z16.
```

this spans [0,31], not [0,15], so i'm confused and I think the last terms ought to be  SHA256(s)_3 ·2^3

similarly the implementation in Sage explicitly cast back to Z_16
```
d = ZZ(d, base=2) # cast to integer
....:     return Z16(d) # cast to Z16
sage: Hash5(b’’)
```

I believe the correct fix is change ` hash function, we use a 5-bit truncation of the SHA256 hash from example 47 ` to 
` hash function, we use a 4-bit truncation of the SHA256 hash from example 47 `

but i'm confused about the intention of the sentence `Since k = |16|2 = 5 and 16 − 2^(k−1) = 0, this hash maps uniformly onto Z16.` Currently it reads as though `5-bit	truncation` was chosen because the integer value 16 requires 5 bits. Perhaps there is simply an off-by-one error given that example above is stops the expansion at k-2 and not k-1.

If i'm correct and the example is wrong, I would be happy to open a PR to correct it.

**Comment by PlanetMacro** [comment]
Yes I agree that the example is wrong, because it included the 2^4 term, while the definition sum to k-2 only. Equation 4.36 wasn't applied correctly.

Also I agree that the sage code might not be the best way to represent the hash because casting to Z16 in the end kind of defies the point of show that it actually hashes to Z_16. 

Code updated.
